language: node_js;
node_js:
  - 8.11.4
install:
  -npm ci
script:
 - npm run test

deploy:
  provide: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: main
after_success:
  - npm run coverage