sudo: false
language: node_js;
node_js:
  - node
install:
  - npm ci

before_script:
  - npm install
  - npm install coveralls

script:
 - npm run coveralls



deploy:
  provide: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: main
after_success:
  - npm run coverage
notifications:
  email: false